// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float4> Result;
float4 _color;
int _axis;

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    float r = (float)id.x / (float)_axis;
    float g = (float)id.y / (float)_axis;
    float b = (float)id.z / (float)_axis;
    Result[id.xyz] = float4(r, g, b, 1) * _color;
}
